# Generated by Django 5.2.4 on 2025-08-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffecontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='manejousuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='manejousuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='mesero',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ManejoUsuario',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
