# Generated by Django 5.2.4 on 2025-10-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos'),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
